# Generated by Django 5.1.4 on 2025-01-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usuario_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='compañía',
        ),
        migrations.AddField(
            model_name='usuario',
            name='compañías',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='core.compañía'),
        ),
    ]
