# Generated by Django 5.1.4 on 2025-01-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_usuario_compañías'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compañía',
            new_name='Compania',
        ),
        migrations.RenameField(
            model_name='compania',
            old_name='correo_electronico',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='compania',
            old_name='dirección',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='compania',
            old_name='teléfono',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='historiadeusuario',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='historiadeusuario',
            old_name='título',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='compañía',
            new_name='Compania',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='historia_de_usuario',
            new_name='historiaDeUsuario',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='título',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='compañías',
            new_name='Compania',
        ),
    ]
