# Generated by Django 5.1.4 on 2025-01-12 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compañía',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('teléfono', models.CharField(max_length=20)),
                ('dirección', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'compania',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripción', models.TextField()),
                ('compañía', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='core.compañía')),
            ],
            options={
                'db_table': 'proyecto',
            },
        ),
        migrations.CreateModel(
            name='HistoriaDeUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('título', models.CharField(max_length=200)),
                ('descripción', models.TextField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias', to='core.proyecto')),
            ],
            options={
                'db_table': 'historiaDeUsuario',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('título', models.CharField(max_length=200)),
                ('descripción', models.TextField()),
                ('comentarios', models.TextField(blank=True)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.estado')),
                ('historia_de_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.historiadeusuario')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.AutoField(primary_key=True, serialize=False)),
                ('compañía', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.compañía')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
