# Generated by Django 5.1.4 on 2025-01-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
