# Generated by Django 5.1.4 on 2025-01-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_usuario_compañía_usuario_compañías'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='compañías',
            field=models.ManyToManyField(blank=True, null=True, related_name='usuarios', to='core.compañía'),
        ),
    ]
