# Generated by Django 5.1.4 on 2025-01-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_compañía_compania_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Compania',
            new_name='compania',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=150),
        ),
    ]
