# Generated by Django 5.1.4 on 2025-01-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_compania_usuario_compania_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='compania',
            field=models.ManyToManyField(blank=True, related_name='cedula', to='core.compania'),
        ),
    ]
